project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - notebooks/*.ipynb
    - docs/fuente_datos.md
    - docs/plan_limpieza.md
    - docs/informe_calidad.md
    - docs/codebook.md
    - docs/revision_cumplimiento.md

website:
  title: "Proyecto 1 · Data Science"
  description: "Obtención y Limpieza de Datos · CC3084"
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: notebooks/01_ingesta_diagnostico_inicial.ipynb
        text: Diagnóstico inicial
      - href: docs/informe_calidad.md
        text: Informe de calidad
      - href: docs/codebook.md
        text: Libro de códigos
    tools:
      - icon: github
        href: https://github.com/Vann06/Proyecto-1-Data-Science

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: show
    code-tools: true
    code-copy: true
    lang: es

execute:
  freeze: auto
